---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant
data:
  configuration.yaml: |
    http:
      cors_allowed_origins:
        - https://hass.lambert.tf
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.244.0.0/16

    # Loads default set of integrations. Do not remove.
    default_config:

    # Text to speech
    tts:
      - platform: google_translate

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    frontend:
      themes: !include_dir_merge_named themes
