---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m0s
  timeout: 5m0s
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: helm-repo-cert-manager
        namespace: flux-system
      version: v1.12.0
  values:
    podDnsConfig:
      options:
      - name: ndots
        value: "1"
