---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate
data:
  config.yml: |
    logger:
      default: debug
    mqtt:
      host: mqtt
    detectors:
      ov:
        type: openvino
        device: AUTO
        model:
          path: /openvino-model/ssdlite_mobilenet_v2.xml
    model:
      width: 300
      height: 300
      input_tensor: nhwc
      input_pixel_format: bgr
      labelmap_path: /openvino-model/coco_91cl_bkgr.txt
    cameras:
      entree1:
        ffmpeg:
          hwaccel_args: preset-vaapi
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - +genpts+discardcorrupt
            - -flags
            - low_delay
            - -strict
            - experimental
            - -analyzeduration
            - 1000M
            - -probesize
            - 1000M
            - -rw_timeout
            - "5000000"
          inputs:
            - path: rtmp://192.168.1.31/bcs/channel0_main.bcs?channel=0&stream=0&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
            #- path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.31:554/h264Preview_01_main
              roles:
                - record
                - rtmp
            - path: rtmp://192.168.1.31/bcs/channel0_ext.bcs?channel=0&stream=0&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
              roles:
                - detect
        detect:
          width: 640
          height: 360
          fps: 7
        objects:
          track:
            - person
            - dog
            - bird
            - cat
            - car
            - bicycle
        zones:
          cour:
            coordinates: 176,141,640,0,640,360,0,360,0,318
            objects:
              - person
              - dog
              - car
              - bicycle
              - bird
              - cat
          horschamp:
            coordinates: 0,0,364,0,374,73,165,131,0,310
            objects:
              - person
              - cat
              - car
        snapshots:
          enabled: True
          timestamp: True
          bounding_box: True
          required_zones:
            - cour
            - horschamp
        record:
          enabled: True
          retain:
            days: 30
            mode: motion
          events:
            required_zones:
              - cour
              - horschamp
            retain:
              default: 10
              mode: active_objects
      entree2:
        ffmpeg:
          hwaccel_args: preset-vaapi
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - +genpts+discardcorrupt
            - -flags
            - low_delay
            - -strict
            - experimental
            - -analyzeduration
            - 1000M
            - -probesize
            - 1000M
            - -rw_timeout
            - "5000000"
          inputs:
            - path: rtmp://192.168.1.31/bcs/channel1_main.bcs?channel=1&stream=0&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
            #- path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.31:554/h264Preview_02_main
              roles:
                - record
                - rtmp
            - path: rtmp://192.168.1.31/bcs/channel1_ext.bcs?channel=1&stream=0&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
              roles:
                - detect
        detect:
          width: 640
          height: 360
          fps: 7
        objects:
          track:
            - person
            - dog
            - cat
            - bird
            - bicycle
        zones:
          allee:
            coordinates: 536,154,491,211,159,190,94,137
            objects:
              - person
              - dog
              - bicycle
              - bird
              - cat
          jardin:
            coordinates: 104,0,268,22,474,27,581,58,546,155,323,170,118,150,78,114
            objects:
              - person
              - dog
              - bicycle
              - bird
              - cat
          entree:
            coordinates: 0,360,640,360,640,0,570,0,404,157,322,191,189,188,114,143,75,51,0,69
            objects:
              - person
              - dog
              - bicycle
              - bird
          porte:
            coordinates: 0,0,106,0,88,122,0,143
            objects:
              - person
              - dog
              - bicycle
        snapshots:
          enabled: True
          timestamp: True
          bounding_box: True
          required_zones:
            - allee
            - jardin
            - entree
            - porte
        record:
          enabled: True
          retain:
            days: 1
            mode: motion
          events:
            required_zones:
              - allee
              - jardin
              - entree
              - porte
            retain:
              default: 5
              mode: active_objects
      jardin1:
        ffmpeg:
          hwaccel_args: preset-vaapi
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - +genpts+discardcorrupt
            - -flags
            - low_delay
            - -strict
            - experimental
            - -analyzeduration
            - 1000M
            - -probesize
            - 1000M
            - -rw_timeout
            - "5000000"
          inputs:
            - path: rtmp://192.168.1.32/bcs/channel0_main.bcs?channel=0&stream=0&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
            #- path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.32:554/h264Preview_01_main
              roles:
                - record
                - rtmp
            - path: rtmp://192.168.1.32/bcs/channel0_ext.bcs?channel=0&stream=0&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
              roles:
                - detect
        detect:
          width: 640
          height: 360
          fps: 7
        objects:
          track:
            - person
            - dog
            - bicycle
            - cat
            - bird
        zones:
          jardin:
            coordinates: 257,45,429,10,454,85,462,123,640,94,640,259,537,360,0,360,0,242
            objects:
              - person
              - dog
              - cat
              - bird
          terrasse_1:
            coordinates: 640,0,640,205,640,114,462,130,461,86,427,0
            objects:
              - person
              - dog
              - cat
              - bird
          allee:
            coordinates: 516,360,640,360,640,213
            objects:
              - person
              - dog
              - cat
              - bird
          horschamp:
            coordinates: 303,40,437,17,426,0,0,0,0,231
            objects:
              - person
              - dog
              - cat
              - bird
        snapshots:
          enabled: True
          timestamp: True
          bounding_box: True
          required_zones:
            - jardin
            - allee
            - terrasse_1
            - horschamp
        record:
          enabled: True
          retain:
            days: 1
            mode: motion
          events:
            required_zones:
              - jardin
              - allee
              - terrasse_1
              - horschamp
            retain:
              default: 5
              mode: active_objects
      jardin2:
        ffmpeg:
          hwaccel_args: preset-vaapi
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - +genpts+discardcorrupt
            - -flags
            - low_delay
            - -strict
            - experimental
            - -analyzeduration
            - 1000M
            - -probesize
            - 1000M
            - -rw_timeout
            - "5000000"
          inputs:
            - path: rtmp://192.168.1.32/bcs/channel1_main.bcs?channel=1&stream=0&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
            #- path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.32:554/h264Preview_02_main
              roles:
                - record
                - rtmp
            - path: rtmp://192.168.1.32/bcs/channel1_ext.bcs?channel=1&stream=0&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
              roles:
                - detect
        detect:
          width: 640
          height: 360
          fps: 7
        objects:
          track:
            - person
            - dog
            - bicycle
            - cat
            - bird
        zones:
          jardin:
            coordinates: 616,159,520,360,331,360,230,265,149,239,0,257,0,120,98,135,64,193,0,257,139,240,196,104,238,97,275,0
            objects:
              - person
              - dog
              - cat
              - bird
          allee:
            coordinates: 0,249,63,148,24,141,0,93,92,77,208,80,211,124,158,241,236,250,323,360,0,360
            objects:
              - person
              - dog
              - cat
              - bird
          abri:
            coordinates: 243,0,25,0,17,53,80,106,219,104
            objects:
              - person
              - dog
              - cat
              - bird
          terrasse_1:
            coordinates: 0,111,0,0,47,4,40,62,92,106
            objects:
              - person
              - dog
              - cat
              - bird
          horschamp:
            coordinates: 640,0,640,360,554,357,554,287,615,165,306,0
            objects:
              - person
              - dog
              - cat
              - bird
        snapshots:
          enabled: True
          timestamp: True
          bounding_box: True
          required_zones:
            - jardin
            - allee
            - abri
            - terrasse_1
            - horschamp
        record:
          enabled: True
          retain:
            days: 1
            mode: motion
          events:
            required_zones:
              - jardin
              - allee
              - abri
              - terrasse_1
              - horschamp
            retain:
              default: 5
              mode: active_objects
      terrasse:
        ffmpeg:
          hwaccel_args: preset-vaapi
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - +genpts+discardcorrupt
            - -flags
            - low_delay
            - -strict
            - experimental
            - -analyzeduration
            - 1000M
            - -probesize
            - 1000M
            - -rw_timeout
            - "5000000"
          inputs:
            - path: rtmp://192.168.1.33/bcs/channel0_main.bcs?channel=0&stream=0&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
            #- path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.33:554/h264Preview_01_main
              roles:
                - record
                - rtmp
            - path: rtmp://192.168.1.33/bcs/channel0_ext.bcs?channel=0&stream=0&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
              roles:
                - detect
        detect:
          width: 640
          height: 360
          fps: 7
        objects:
          track:
            - person
            - dog
            - cat
            - bird
        zones:
          terrasse_2:
            coordinates: 640,360,640,0,387,0,382,30,0,206,0,360
            objects:
              - person
              - dog
              - cat
              - bird
          horschamp:
            coordinates: 0,0,0,211,425,0,403,0
            objects:
              - person
        snapshots:
          enabled: True
          timestamp: True
          bounding_box: True
          required_zones:
            - terrasse_2
            - horschamp
        record:
          enabled: True
          retain:
            days: 1
            mode: motion
          events:
            required_zones:
              - terrasse_2
              - horschamp
            retain:
              default: 5
              mode: active_objects
