---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frigate
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100G
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frigateconfig
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
