---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 5m0s
  url: https://guerzon.github.io/vaultwarden
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 10m
  chart:
    spec:
      chart: vaultwarden
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
      version: 0.32.1
  values:
    domain: "https://pass.lambert.tf"
    signupDomains: "lambert.tf"
    timeZone: "Europe/Paris"
    storage:
      existingVolumeClaim:
          claimName: "vaultwarden-data"
          dataPath: "/data"
          attachmentsPath: "/data/attachments"
    yubico:
      clientId: "113338"
      existingSecret: vaultwarden
      secretKey:
        existingSecretKey: YUBICO_SECRET_KEY
    adminToken:
      existingSecret: vaultwarden
      existingSecretKey: ADMIN_TOKEN
    ingress:
      enabled: true
      class: "nginx"
      additionalAnnotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hostname: pass.lambert.tf
      tlsSecret: "pass-lambert-tf-ssl"
