---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 10m0s
  timeout: 5m0s
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: helm-repo-traefik
        namespace: flux-system
      version: v24.0.0
  values:
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      repository: "rancher/mirrored-library-traefik"
      tag: "2.9.10"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    service:
      ipFamilyPolicy: "PreferDualStack"
      spec:
        externalTrafficPolicy: Local
    nodeSelector:
      node-role.kubernetes.io/master: true
